name: ntx-feature-workflow

on:
  push:
    branches:
      - "feature"
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        run: |
          docker build -t $GITHUB_REPOSITORY:GITHUB_REF .
      - name: Check Docker Image
        run: |
          docker images 