name: ntx-feature-workflow

on:
  push:
    branches:
      - "feature"
env:
  GCP_REGION: ${{ vars.GCP_REGION }}
  DOCKER_IMAGE_NAME: ntx-img-app
  REPO_NAME: ntx-app-repo

jobs:
  terraformGCP:
    name: terraform GCP
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
    #authentication
    - name: auth to gcp
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.NTX_GCP_SA }}'

      #set up gcp
    - name: set up gcp sdk
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.NTX_GCP_PROJECT_ID }}

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      
        
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: |
        cd terraform
        terraform init --upgrade
        terraform apply -auto-approve \
          -var="project_id=${{ vars.GCP_PROJECT_ID }}" \
          -var="region=${{ vars.GCP_REGION }}" \
          -var="repo_id=${{ vars.GCP_REPO_ID }}"
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.NTX_GCP_SA }}'
      #set up gcp
      - name: set up gcp sdk
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.NTX_GCP_PROJECT_ID }}

      - name: "Artifact Registry auth"
        run: gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev
        
      - name: Build Docker Image
        run: |
          IMAGE_URL=$GCP_REGION-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/$REPO_NAME/$DOCKER_IMAGE_NAME:latest
          docker build -t $IMAGE_URL .

      - name: Check Docker Image
        run: |
          docker images

      - name: Publish to GCR
        run: |
          docker push $IMAGE_URL