name: ntx-feature-workflow

on:
  push:
    branches:
      - "feature"
env:
  APP_TAG: ${{ github.run_id }}
  GCP_REGISTRY: "asia-southeast1-docker.pkg.dev/charged-kiln-460511-p8/ntx-devops-test"
  GCP_REGION: ${{ vars.GCP_REGION }}
  GCP_REPO_NAME: ${{ vars.GCP_REPO_ID }}

jobs:
  terraformGCP:
    name: terraform GCP
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
    #authentication
    - name: auth to gcp
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.NTX_GCP_SA }}'

      #set up gcp
    - name: set up gcp sdk
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.NTX_GCP_PROJECT_ID }}

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      
        
    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: |
        cd terraform
        terraform init --upgrade
        terraform apply -auto-approve \
          -var="project_id=${{ secrets.NTX_GCP_PROJECT_ID }}" \
          -var="region=$GCP_REGION" \
          -var="repo_id=$GCP_REPO_ID"
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.NTX_GCP_SA }}'
      #set up gcp
      - name: set up gcp sdk
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.NTX_GCP_PROJECT_ID }}

      - name: Build Docker Image
        run: |
          docker build -t $GCP_REGISTRY:$APP_TAG .
      - name: Check Docker Image
        run: |
          docker images
      - name: "Artifact Registry auth"
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev
      - name: Publish to GCR
        run: |
          docker push "$GCP_REGISTRY:$APP_TAG"