name: ntx-feature-workflow

on:
  push:
    branches:
      - "feature"
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CICD_SA }}"
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.GCP_REGISTRY }}:$GITHUB_REF .
      - name: Check Docker Image
        run: |
          docker images 