name: ntx-feature-workflow

on:
  push:
    branches:
      - "feature"
env:
  APP_TAG: ${{ github.run_id }}
  GCP_REGISTRY: "asia-southeast1-docker.pkg.dev/charged-kiln-460511-p8/ntx-devops-test"
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_CICD_SA }}"
      - name: Build Docker Image
        run: |
          docker build -t $GCP_REGISTRY:$APP_TAG .
      - name: Check Docker Image
        run: |
          docker images
      - name: "Artifact Registry auth"
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev
      - name: Publish to GCR
        run: |
          docker push "$GCP_REGISTRY:$APP_TAG"